#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/florafauna-ai/flora-go,github.com/stainless-sdks/florafauna-ai-go"

echo "==> Building flora"
go build ./cmd/flora
